export enum Error {
  NONE = '',
  DEFAULT = 'Something went wrong. Please try again',
  EMPTY_NAME = 'Name is required',
  EMPTY_FIELDS = 'Fill up the fields',
  EMPTY_PASSWORD = 'Password is required',
  EMPTY_EMAIL = 'Email is required',
  EMPTY_CITY = 'City should not be empty',
  EMPTY_MESSAGE = 'Message cannot be empty',
  EMPTY_FIRST_NAME = 'First name should not be empty',
  EMPTY_LAST_NAME = 'Last name should not be empty',
  EMPTY_WAREHOUSE = 'Waerhouse should not be empty',
  EMPTY_PHONE_NUMBER = 'Phone number should not be empty',
  INVALID_EMAIL = 'Invalid email format',
  INVALID_FIRST_NAME = 'Please enter a valid First name',
  INVALID_LAST_NAME = 'Please enter a valid Last name',
  INVALID_PHONE_NUMBER = 'Please enter a valid Phone number',
  INVALID_CARD_NUMBER = 'Invalid card number',
  INVALID_EXPIRY_DATE = 'Invalid expiry date',
  INVALID_CVV = 'Invalid CVV',
  SUCCESS_LOGIN = "You've successfully logged in",
  SUCCESS_SIGN_UP = "You've successfully signed up",
  SUCCESS_FORM_MESSAGE = 'Message sent',
  SUCCESS_SUBSCRIPTION = "You've successfully subscribed",
}
